#!/usr/bin/env bash
# Cloud Agent `start` phase: per-boot bring-up. Starts the Docker daemon, the
# local Supabase stack, bootstraps the database, and writes .env.local. Safe to
# run repeatedly. The Next.js dev server itself runs as a `terminals` entry.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

echo "==> Ensuring Docker daemon is running"
if ! docker info >/dev/null 2>&1; then
  sudo dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do [ -S /var/run/docker.sock ] && break; sleep 1; done
fi
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true

echo "==> Disabling bridge netfilter so container-to-container traffic switches at L2"
# Docker turns bridge-nf-call-iptables back on when it creates a network, and in
# this nested VM the iptables path drops inter-container packets. Keep it off
# through Supabase startup with a short background enforcer.
set_brnf0() {
  echo 0 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables >/dev/null 2>&1 || true
  echo 0 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables >/dev/null 2>&1 || true
}
set_brnf0
( for _ in $(seq 1 180); do set_brnf0; sleep 0.5; done ) &
enforcer=$!

echo "==> Starting local Supabase stack"
if ! supabase status >/dev/null 2>&1; then
  supabase start
fi

echo "==> Bootstrapping database schema + seed"
bash "$ROOT/scripts/dev/setup-local-db.sh"

echo "==> Writing .env.local from local Supabase credentials"
eval "$(supabase status -o env 2>/dev/null | sed 's/^/SB_/')"
cat > "$ROOT/.env.local" <<EOF
# Auto-generated by scripts/dev/cloud-start.sh — local development only.
NEXT_PUBLIC_SUPABASE_URL=${SB_API_URL//\"/}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SB_ANON_KEY//\"/}
SUPABASE_SERVICE_ROLE_KEY=${SB_SERVICE_ROLE_KEY//\"/}

INTERNAL_AUTH_USER=ecm
INTERNAL_AUTH_PASSWORD=ecm-dev-password

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
OWNER_EMAIL=owner@eastcoastmechanical.org
HOURLY_LABOR_RATE=150
CRON_SECRET=dev-cron-secret

# Placeholders so SDK clients that construct at import (Stripe, Claude, Resend)
# don't throw. These integrations are non-functional without real keys.
ANTHROPIC_API_KEY=sk-ant-dummy-local
STRIPE_SECRET_KEY=sk_test_dummy_local
RESEND_API_KEY=re_dummy_local
EOF

echo "==> Seeding a development staff login"
SUPABASE_DB_URL="${SB_DB_URL//\"/}" SUPABASE_API_URL="${SB_API_URL//\"/}" \
  SUPABASE_SERVICE_ROLE_KEY="${SB_SERVICE_ROLE_KEY//\"/}" \
  bash "$ROOT/scripts/dev/seed-dev-login.sh" || echo "    (dev login seed skipped)"

kill "$enforcer" 2>/dev/null || true
set_brnf0

echo "==> start complete — Supabase is up, .env.local written. Next.js dev runs in its terminal."
